name: Website Build

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 1.8
            - uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Running Jar File
              run: java -jar binaries/ssj.jar --build
            - name: Deploy
            - uses: JamesIves/github-pages-deploy-action@4.0.0
              with:
                  branch: gh-pages
                  folder: dist
